# roles/transmission/defaults/main.yml

# Куда качать торренты
transmission_download_dir: /home/chebureck/Downloads/Torrents

# Настройки RPC (веб-интерфейс)
transmission_rpc_port: 9091
# transmission_rpc_username: admin
# transmission_rpc_password: "changeme"
transmission_rpc_auth_required: false

# Настройки соединения
transmission_peer_port: 51413
transmission_port_forwarding_enabled: false

# Whitelist — отключаем оба, чтобы был доступ и по IP и по hostname
transmission_rpc_whitelist_enabled: false
transmission_rpc_host_whitelist_enabled: false

# Поведение при загрузке
transmission_incomplete_dir_enabled: false
transmission_rename_partial_files: false