# roles/transmission/tasks/main.yml
---
- name: Install Transmission daemon
  apt:
    name: transmission-daemon
    state: present
    update_cache: yes

- name: Add chebureck to debian-transmission group  # добавление пользователя chebureck в группу debian-transmission
  user:
    name: chebureck
    groups: debian-transmission
    append: yes

- name: Create systemd override directory for Transmission
  file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory
    mode: "0755"

- name: Override Transmission service user
  copy:
    dest: /etc/systemd/system/transmission-daemon.service.d/override.conf
    content: |
      [Service]
      User=chebureck
      Group=chebureck
      ExecStart=
      ExecStart=/usr/bin/transmission-daemon -f --log-level=error -g /etc/transmission-daemon
  notify: Reload systemd daemon

- name: Ensure download directory exists
  file:
    path: "{{ transmission_download_dir }}"
    state: directory
    mode: "0755"
  ignore_errors: yes   # NTFS игнорирует chown, это ок

# Сухой прогон — только проверяем, изменился бы конфиг
- name: Check if config would change
  template:
    src: settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: chebureck
    group: debian-transmission
    mode: "0664"
  check_mode: yes
  register: config_check

# Останавливаем ТОЛЬКО если конфиг изменился
- name: Stop Transmission if config changed
  service:
    name: transmission-daemon
    state: stopped
  when: config_check.changed

- name: Deploy Transmission config from template
  template:
    src: settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: chebureck
    group: debian-transmission
    mode: "0664"

- name: Ensure Transmission is running and enabled
  service:
    name: transmission-daemon
    state: started
    enabled: yes
